### ISSUE TITLE
FreeBSD 12.2 and 13.0 are EoL. They are succeeded by 12.4 and 13.2.

### ISSUE THREAD

**Issue by Crest** [goneri/bsd-cloud-image.org#3]
Thank you for making FreeBSD easier to consume. The FreeBSD versions listed on bsd-cloud-image.org (12.2 and 13.0) have reached their official end of life. For FreeBSD this means they no longer receive security and bug fixes and the official binary package repositories are no longer compatible with their older unsupported ABI. Both major releases (12.x and 13.x) already packaged as images are still supported, but they each require an update to the latest minor release in the corresponding major release (12.4 and 13.2).

Are there any known problems blocking the release of newer FreeBSD versions as images and if so which contributions would be helpful to overcome them?

**Comment by goneri** [comment]
Hi @Crest,

Thank you for asking. I've got a FreeBSD 13.1 image ready but I cannot get the networking to work with OpenStack (OVH, VexxHost) an I delayed several times the upload because of that.
The DHCP is reachable, I get the lease but FreeBSD doesn't set the right routes to reach the gateway. This being said, I need a bit more time to clearly describe the problem.

Could you be interested to  help me troubleshoot? I can share a copy of the .qcow2.

**Comment by goneri** [comment]
I just gave a stry to FreeBSD 13.2 on OVH to see if I still face the same problem. This time, it sets the default route properly but I still cannot get any IP traffic, I cannot ping the gateway and the DNS too. I suspect a problem with the vtnet drive.

**Comment by goneri** [comment]
I opened https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=270983 to trace the problem and I will just advice the users to switch to the e1000 driver.

**Comment by goneri** [comment]
Ok, it was an ambarassing misconfiguration from my side.... The new images  will soon be published.

**Comment by goneri** [comment]
13.2 has just been uploaded. I will do 12.4 tomorrow.
